# Generated by Django 5.2.8 on 2025-12-04 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
