# Generated by Django 5.2.8 on 2025-12-07 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricola',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'The matricola must contain exactly 6 digits')], verbose_name='Matricola'),
        ),
    ]
