# Generated by Django 5.2.8 on 2025-11-29 15:15

from django.db import migrations


def create_goals(apps, _):
    Goal = apps.get_model("core", "Goal")
    data = [
        {"title": "SETUP GIT REPOSITORIES",
         "description": """Setup git repositories (eg. GitHub or GitLab), send me a link for each sub-project (back-end and
                        front-ends), and properly present the final result with a short oral presentation or video
                        - Alternative if you don't know git: Dropbox, Drive or anything that you can share with me by sending a link""",
        "points": 1},
        {"title": "SETUP DJANGO", "description": "Setup Django REST Framework with CORS and documentation", "points": 1},
        {"title": "DEFINE ONE MODEL", "description": "Define at least one model (don't overdo)", "points": 1},
        {"title": "REST API (WITH VALIDATION)", "description": "Expose your models with your API in a proper way (validate incoming data)", "points": 1},
        {"title": "AUTHN AND AUTHZ", "description": "Implement authentication and authorization in a proper way", "points": 1},
        {"title": "DJANGO TEST COVERAGE >90%", "description": "Test the back-end (coverage of your code >90%)", "points": 1},
        {"title": "PYTHON TUI", "description": "Implement a Python TUI front-end", "points": 2},
        {"title": "TUI TEST COVERAGE >90%", "description": "Test the TUI front-end (coverage of your code >90%)", "points": 1},
        {"title": "GUI", "description": "Implement a browser or mobile or desktop front-end with any programming language or framework you like (and you already know)", "points": 1},
    ]
    for item in data:
        Goal.objects.create(**item)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_goals),
    ]