# Generated by Django 5.2.8 on 2025-11-29 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_populate_goals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupgoals',
            options={'verbose_name': 'Group Goal', 'verbose_name_plural': 'Group Goals'},
        ),
        migrations.AddField(
            model_name='user',
            name='matricola',
            field=models.CharField(default='000000', unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'La matricola deve avere 6 cifre numeriche')], verbose_name='Matricola'),
            preserve_default=False,
        ),
    ]
