# Generated by Django 5.2.8 on 2025-11-30 08:40

from django.db import migrations

def create_topics(apps, _):
    Topic = apps.get_model("core", "Topic")
    data = [
        {"title": "E-commerce Platform"},
        {"title": "Social Network"},
        {"title": "Task Manager"},
        {"title": "Blog Platform"},
        {"title": "Learning Management System"},
        {"title": "Restaurant Booking"},
        {"title": "Library Management"},
        {"title": "Event Manager"},
        {"title": "Fitness Tracker"},
    ]
    for item in data:
        Topic.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_groupgoals_options_user_matricola'),
    ]

    operations = [
         migrations.RunPython(create_topics),
    ]
