# Generated by Django 5.2.8 on 2025-11-30 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_populate_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricola',
            field=models.CharField(validators=[django.core.validators.RegexValidator('^\\d{6}$', 'La matricola deve avere 6 cifre numeriche')], verbose_name='Matricola'),
        ),
    ]
