# Generated by Django 5.2.8 on 2025-12-01 18:37

from django.db import migrations

def create_topics(apps, _):
    Topic = apps.get_model("group_projects", "Topic")
    data = [
        {"title": "E-commerce Platform"},
        {"title": "Social Network"},
        {"title": "Task Manager"},
        {"title": "Blog Platform"},
        {"title": "Learning Management System"},
        {"title": "Restaurant Booking"},
        {"title": "Library Management"},
        {"title": "Event Manager"},
        {"title": "Fitness Tracker"},
    ]
    for item in data:
        Topic.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('group_projects', '0003_create_goals'),
    ]

    operations = [
         migrations.RunPython(create_topics),
    ]
